#!/usr/bin/env python3
"""Generate the reviewable skill catalog from metadata and anonymous usage counts."""
import argparse
import json
from pathlib import Path
import sys

from manage import load_catalog, metadata

ROOT = Path(__file__).resolve().parents[1]


def render(root):
    lock = load_catalog(root)
    usage = json.loads((root / "data/usage-2026-10-07.json").read_text())
    rows = usage["skills"]
    lines = ["<!-- Generated by scripts/catalog.py. Do not edit manually. -->", "# Каталог скиллов", "",
             f"Набор: {len(lock['skills'])} скилла. Период наблюдений: {usage['period']}. "
             "Сортировка по числу подтверждённых применений, затем по имени.", "",
             "Чтение SKILL.md или вызов Skill считается применением один раз за ход. "
             "Ноль означает отсутствие наблюдения за период. В статистике представлены только "
             "скиллы текущего набора; применения одинаковых имён из разных хостов и копий объединены.", "",
             "| Скилл | Применений | Задач | Происхождение | Зависимости | Назначение |",
             "|---|---:|---:|---|---|---|"]
    ordered = sorted(lock["skills"], key=lambda name: (-rows.get(name, {}).get("uses", 0), name))
    for name in ordered:
        record = lock["skills"][name]
        info, _ = metadata(root / "skills" / name)
        description = " ".join(info["description"].split()).replace("|", "\\|").replace("—", "-")
        if len(description) > 200:
            description = description[:197].rsplit(" ", 1)[0] + "…"
        observed = rows.get(name, {})
        origin = {"mattpocock": "Matt Pocock, адаптирован", "openai": "OpenAI, первоисточник"}.get(
            record["origin"], "Локальный снимок")
        deps = ", ".join(f"`{dep}`" for dep in record.get("dependencies", [])) or "-"
        lines.append(f"| [{name}](../skills/{name}/SKILL.md) | {observed.get('uses', 0)} | "
                     f"{observed.get('tasks', 0)} | {origin} | {deps} | {description} |")
    lines += ["", "Состояние upstream и исходные хеши: [sources.lock.json](../sources.lock.json). "
              "Решения по заимствованиям: [сравнение с Matt Pocock](matt-pocock-comparison.md).", "",
              "Статистика используется для приоритизации. Она не доказывает качество или экономию токенов; "
              "сырые журналы, сообщения и идентификаторы задач в репозиторий не включены."]
    return "\n".join(lines) + "\n"


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="Fail if the generated catalog is outdated")
    args = parser.parse_args()
    target = ROOT / "docs/catalog.md"
    expected = render(ROOT)
    if args.check:
        if not target.exists() or target.read_text() != expected:
            print("Catalog is outdated. Run make catalog.")
            return 1
        print("Catalog is current.")
    else:
        target.parent.mkdir(exist_ok=True)
        target.write_text(expected)
        print("Updated docs/catalog.md.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
